/// Flutter icons ZerodhaApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ZerodhaApp
///      fonts:
///       - asset: fonts/ZerodhaApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ZerodhaApp {
  ZerodhaApp._();

  static const _kFontFam = 'ZerodhaApp';
  static const String? _kFontPkg = null;

  static const IconData portfolio = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tools = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
